revisionHistoryLimit: 0

image:
  registry: 'registryName'.azurecr.io
  name: blackbox
  version: latest
  imagePullPolicy: Always

deployment:
  replicas: 1
  port: 9115
  annotations:
    prometheus.io/port: "9115"
    prometheus.io/scrape: "true"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1

# ingress can be enabled for debugging
ingress:
  enabled: false
  host: 'blackboxUrl'