# prometheus.yml
global:
    scrape_interval: 10s
scrape_configs:
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [health_ok]
    static_configs:
      - targets:
        - sentry:9000/_health/
        - weblate:80/healthz/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 # The blackbox exporter's real hostname:port.